name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "629ada79e28d5d29f894f39fb14a0a94d2eaf3d7eeffbe76a7f32bfce3832631"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
