name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f540422e3acaa55f4c6a333c1267b24fff9fedc485a664dc774fa3af2a6ec716"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
