name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b17975732448993bac16d51c5d3a0ff7f48ad6ee1248cd70fd1c1f9fe304e93"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
