name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7de0ab90429575b31748c0e4804f143dfcbc0960d4074d1c97272ae95b0c72ac"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
