name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32a5ee489087fc04153ff25e8efd900d8f19d668e41d6cce0c431b20646ec8d"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
