name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd7eb75ace7c8c07813fe1390dd9e72c3897c459fed3ef854cf93f9367a9e793"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
