name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b728e4da8432a87413744932dd5a3e9ab9016132f41073eed4428ab8e423a5e3"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
