name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6505b8729e389b367d31c8557817200c2c85f8b3110e825cbe5c960a8949757e"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
