name = "Wiz Craft"
author = "The Great Wizard Council"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40e16cd6d1aa6bca78421afb5e5c805aca522ff59abcbd700a56055f587272a0"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
