name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13518176b2405b8339b67066284bf030ca96a433670d1efcb93860b0c690d40c"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
