name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "593290680419071957a54961f5c1be64347829fc3b03b24a3ad0c9d658177627"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
