name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae5974f4892749d3010653fe98019b488071039086c79e02a959fadde0af93bc"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
