name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58bf3d78298c90c3b9d96fb815ea0cf0a8cc7bf7f6425851a08ac559fef8bc39"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
