name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1bb2a42f4f4698869903179e47bb07af385b86d44a475dbd1a3f8bde68e8b92"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
