name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a76646262fb65c511f20cc3f084589269974b668070ced63ccad656a96381f62"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
