name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a261f723ed12282a9b09cd1fd7cf33f3e7264348148f95a0b13c768e8811869"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
