name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a183a1f87bd4ae30b8ac08126d9a0226434a04a107190c763a61b008e36ec776"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
