name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "797954028d4db8b5a4b18915b2bb1727ebedaffc4e47b89ae3cf54320445feea"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
