name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acb6eb802ce55bd23bc1a9df2112ee19094f6ee922ebcc23a2865a3719d3e1ad"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
