name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbeb0dbfa4af5b4b8f56edebd78bb508f4b1556e0ff83b9ca782ad2f67617d2e"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
