name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a06a68f92369225011e51ffde43945ef993096351b33e2ae3e1eb0caf34b349"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
