name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f3ef458e623e996c6aa29d147ce12bf64a2c3fd15ba4b07f92275e22172f399"

[versions]
minecraft = "1.19.2"
quilt = "0.21.0-beta.3"
