name = "WizCraft"
author = "The Great Wizard Council"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1eac015b3bb803175cfe6ef9e229635e156be4f281e8ca56aede866628210195"

[versions]
minecraft = "1.19.2"
quilt = "0.20.2"
